"""Make email nullable

Revision ID: 121f06c05dc9
Revises: 86c235259e1f
Create Date: 2025-03-26 17:14:42.699954+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121f06c05dc9'
down_revision: Union[str, None] = '86c235259e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores', 'is_disabled')
    
    # Make email nullable for users table
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('is_disabled', sa.BOOLEAN(), nullable=True))
    
    # Make email non-nullable again
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###