"""add_chore_range_reward_cooldown_disable

Revision ID: 86c235259e1f
Revises: 7a861e4fb8b6
Create Date: 2025-03-26 01:40:23.079669+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c235259e1f'
down_revision: Union[str, None] = '7a861e4fb8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('min_reward', sa.Float(), nullable=True))
    op.add_column('chores', sa.Column('max_reward', sa.Float(), nullable=True))
    op.add_column('chores', sa.Column('is_range_reward', sa.Boolean(), nullable=True))
    op.add_column('chores', sa.Column('cooldown_days', sa.Integer(), nullable=True))
    op.add_column('chores', sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chores', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores', 'is_disabled')
    op.drop_column('chores', 'completion_date')
    op.drop_column('chores', 'cooldown_days')
    op.drop_column('chores', 'is_range_reward')
    op.drop_column('chores', 'max_reward')
    op.drop_column('chores', 'min_reward')
    # ### end Alembic commands ###